# Generated by Django 5.2.8 on 2025-11-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('no_of_guests', models.SmallIntegerField(default=6)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
